// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.0
// source: api/control/v1/control.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_ARCHITECT   Role = 1
	Role_ROLE_EXECUTOR    Role = 2
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_ARCHITECT",
		2: "ROLE_EXECUTOR",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_ARCHITECT":   1,
		"ROLE_EXECUTOR":    2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_api_control_v1_control_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_api_control_v1_control_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{0}
}

type Availability int32

const (
	Availability_AVAILABILITY_UNSPECIFIED Availability = 0
	Availability_AVAILABILITY_FREE        Availability = 1
	Availability_AVAILABILITY_BUSY        Availability = 2
	Availability_AVAILABILITY_DRAINING    Availability = 3
)

// Enum value maps for Availability.
var (
	Availability_name = map[int32]string{
		0: "AVAILABILITY_UNSPECIFIED",
		1: "AVAILABILITY_FREE",
		2: "AVAILABILITY_BUSY",
		3: "AVAILABILITY_DRAINING",
	}
	Availability_value = map[string]int32{
		"AVAILABILITY_UNSPECIFIED": 0,
		"AVAILABILITY_FREE":        1,
		"AVAILABILITY_BUSY":        2,
		"AVAILABILITY_DRAINING":    3,
	}
)

func (x Availability) Enum() *Availability {
	p := new(Availability)
	*p = x
	return p
}

func (x Availability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Availability) Descriptor() protoreflect.EnumDescriptor {
	return file_api_control_v1_control_proto_enumTypes[1].Descriptor()
}

func (Availability) Type() protoreflect.EnumType {
	return &file_api_control_v1_control_proto_enumTypes[1]
}

func (x Availability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Availability.Descriptor instead.
func (Availability) EnumDescriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{1}
}

type ProviderSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        string                 `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Effort        string                 `protobuf:"bytes,4,opt,name=effort,proto3" json:"effort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderSettings) Reset() {
	*x = ProviderSettings{}
	mi := &file_api_control_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderSettings) ProtoMessage() {}

func (x *ProviderSettings) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderSettings.ProtoReflect.Descriptor instead.
func (*ProviderSettings) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *ProviderSettings) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *ProviderSettings) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProviderSettings) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ProviderSettings) GetEffort() string {
	if x != nil {
		return x.Effort
	}
	return ""
}

type PresenceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Provider        *ProviderSettings      `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Availability    Availability           `protobuf:"varint,2,opt,name=availability,proto3,enum=botspace.control.v1.Availability" json:"availability,omitempty"`
	ProjectMappings []string               `protobuf:"bytes,3,rep,name=project_mappings,json=projectMappings,proto3" json:"project_mappings,omitempty"`
	Tools           []string               `protobuf:"bytes,4,rep,name=tools,proto3" json:"tools,omitempty"`
	ExecutionPolicy string                 `protobuf:"bytes,5,opt,name=execution_policy,json=executionPolicy,proto3" json:"execution_policy,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PresenceRequest) Reset() {
	*x = PresenceRequest{}
	mi := &file_api_control_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceRequest) ProtoMessage() {}

func (x *PresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceRequest.ProtoReflect.Descriptor instead.
func (*PresenceRequest) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *PresenceRequest) GetProvider() *ProviderSettings {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *PresenceRequest) GetAvailability() Availability {
	if x != nil {
		return x.Availability
	}
	return Availability_AVAILABILITY_UNSPECIFIED
}

func (x *PresenceRequest) GetProjectMappings() []string {
	if x != nil {
		return x.ProjectMappings
	}
	return nil
}

func (x *PresenceRequest) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *PresenceRequest) GetExecutionPolicy() string {
	if x != nil {
		return x.ExecutionPolicy
	}
	return ""
}

type PresenceResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RunnerId        string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	ProjectId       string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Role            Role                   `protobuf:"varint,3,opt,name=role,proto3,enum=botspace.control.v1.Role" json:"role,omitempty"`
	CredentialEpoch uint64                 `protobuf:"varint,4,opt,name=credential_epoch,json=credentialEpoch,proto3" json:"credential_epoch,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PresenceResponse) Reset() {
	*x = PresenceResponse{}
	mi := &file_api_control_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceResponse) ProtoMessage() {}

func (x *PresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceResponse.ProtoReflect.Descriptor instead.
func (*PresenceResponse) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *PresenceResponse) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *PresenceResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *PresenceResponse) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *PresenceResponse) GetCredentialEpoch() uint64 {
	if x != nil {
		return x.CredentialEpoch
	}
	return 0
}

type InspectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectRequest) Reset() {
	*x = InspectRequest{}
	mi := &file_api_control_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectRequest) ProtoMessage() {}

func (x *InspectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectRequest.ProtoReflect.Descriptor instead.
func (*InspectRequest) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *InspectRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type InspectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Revision      string                 `protobuf:"bytes,3,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectResponse) Reset() {
	*x = InspectResponse{}
	mi := &file_api_control_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectResponse) ProtoMessage() {}

func (x *InspectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectResponse.ProtoReflect.Descriptor instead.
func (*InspectResponse) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *InspectResponse) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *InspectResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *InspectResponse) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

type Resume struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CommittedCursor uint64                 `protobuf:"varint,1,opt,name=committed_cursor,json=committedCursor,proto3" json:"committed_cursor,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Resume) Reset() {
	*x = Resume{}
	mi := &file_api_control_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resume) ProtoMessage() {}

func (x *Resume) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resume.ProtoReflect.Descriptor instead.
func (*Resume) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *Resume) GetCommittedCursor() uint64 {
	if x != nil {
		return x.CommittedCursor
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        uint64                 `protobuf:"varint,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_api_control_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *Ack) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *Ack) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type Vote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DecisionId    string                 `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Round         uint32                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	ProposalHash  string                 `protobuf:"bytes,3,opt,name=proposal_hash,json=proposalHash,proto3" json:"proposal_hash,omitempty"`
	Choice        string                 `protobuf:"bytes,4,opt,name=choice,proto3" json:"choice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vote) Reset() {
	*x = Vote{}
	mi := &file_api_control_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vote) ProtoMessage() {}

func (x *Vote) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vote.ProtoReflect.Descriptor instead.
func (*Vote) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *Vote) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *Vote) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *Vote) GetProposalHash() string {
	if x != nil {
		return x.ProposalHash
	}
	return ""
}

func (x *Vote) GetChoice() string {
	if x != nil {
		return x.Choice
	}
	return ""
}

type Proposal struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DecisionId       string                 `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Round            uint32                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	MaterialRevision string                 `protobuf:"bytes,3,opt,name=material_revision,json=materialRevision,proto3" json:"material_revision,omitempty"`
	CanonicalContent []byte                 `protobuf:"bytes,4,opt,name=canonical_content,json=canonicalContent,proto3" json:"canonical_content,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Proposal) Reset() {
	*x = Proposal{}
	mi := &file_api_control_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposal) ProtoMessage() {}

func (x *Proposal) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proposal.ProtoReflect.Descriptor instead.
func (*Proposal) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *Proposal) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *Proposal) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *Proposal) GetMaterialRevision() string {
	if x != nil {
		return x.MaterialRevision
	}
	return ""
}

func (x *Proposal) GetCanonicalContent() []byte {
	if x != nil {
		return x.CanonicalContent
	}
	return nil
}

type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId  string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	AttemptEpoch  uint64                 `protobuf:"varint,2,opt,name=attempt_epoch,json=attemptEpoch,proto3" json:"attempt_epoch,omitempty"`
	ContractHash  string                 `protobuf:"bytes,3,opt,name=contract_hash,json=contractHash,proto3" json:"contract_hash,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Question      string                 `protobuf:"bytes,5,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_api_control_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{9}
}

func (x *Question) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *Question) GetAttemptEpoch() uint64 {
	if x != nil {
		return x.AttemptEpoch
	}
	return 0
}

func (x *Question) GetContractHash() string {
	if x != nil {
		return x.ContractHash
	}
	return ""
}

func (x *Question) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Question) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type Progress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId  string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	AttemptEpoch  uint64                 `protobuf:"varint,2,opt,name=attempt_epoch,json=attemptEpoch,proto3" json:"attempt_epoch,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_api_control_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{10}
}

func (x *Progress) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *Progress) GetAttemptEpoch() uint64 {
	if x != nil {
		return x.AttemptEpoch
	}
	return 0
}

func (x *Progress) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Progress) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId  string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	AttemptEpoch  uint64                 `protobuf:"varint,2,opt,name=attempt_epoch,json=attemptEpoch,proto3" json:"attempt_epoch,omitempty"`
	ContractHash  string                 `protobuf:"bytes,3,opt,name=contract_hash,json=contractHash,proto3" json:"contract_hash,omitempty"`
	Commit        string                 `protobuf:"bytes,4,opt,name=commit,proto3" json:"commit,omitempty"`
	Artifacts     []string               `protobuf:"bytes,5,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	Evidence      []byte                 `protobuf:"bytes,6,opt,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_api_control_v1_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{11}
}

func (x *Result) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *Result) GetAttemptEpoch() uint64 {
	if x != nil {
		return x.AttemptEpoch
	}
	return 0
}

func (x *Result) GetContractHash() string {
	if x != nil {
		return x.ContractHash
	}
	return ""
}

func (x *Result) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *Result) GetArtifacts() []string {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *Result) GetEvidence() []byte {
	if x != nil {
		return x.Evidence
	}
	return nil
}

type RunnerFrame struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*RunnerFrame_Resume
	//	*RunnerFrame_Ack
	//	*RunnerFrame_Vote
	//	*RunnerFrame_Proposal
	//	*RunnerFrame_Question
	//	*RunnerFrame_Progress
	//	*RunnerFrame_Result
	Body          isRunnerFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerFrame) Reset() {
	*x = RunnerFrame{}
	mi := &file_api_control_v1_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerFrame) ProtoMessage() {}

func (x *RunnerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerFrame.ProtoReflect.Descriptor instead.
func (*RunnerFrame) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{12}
}

func (x *RunnerFrame) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RunnerFrame) GetBody() isRunnerFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RunnerFrame) GetResume() *Resume {
	if x != nil {
		if x, ok := x.Body.(*RunnerFrame_Resume); ok {
			return x.Resume
		}
	}
	return nil
}

func (x *RunnerFrame) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Body.(*RunnerFrame_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *RunnerFrame) GetVote() *Vote {
	if x != nil {
		if x, ok := x.Body.(*RunnerFrame_Vote); ok {
			return x.Vote
		}
	}
	return nil
}

func (x *RunnerFrame) GetProposal() *Proposal {
	if x != nil {
		if x, ok := x.Body.(*RunnerFrame_Proposal); ok {
			return x.Proposal
		}
	}
	return nil
}

func (x *RunnerFrame) GetQuestion() *Question {
	if x != nil {
		if x, ok := x.Body.(*RunnerFrame_Question); ok {
			return x.Question
		}
	}
	return nil
}

func (x *RunnerFrame) GetProgress() *Progress {
	if x != nil {
		if x, ok := x.Body.(*RunnerFrame_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *RunnerFrame) GetResult() *Result {
	if x != nil {
		if x, ok := x.Body.(*RunnerFrame_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isRunnerFrame_Body interface {
	isRunnerFrame_Body()
}

type RunnerFrame_Resume struct {
	Resume *Resume `protobuf:"bytes,2,opt,name=resume,proto3,oneof"`
}

type RunnerFrame_Ack struct {
	Ack *Ack `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

type RunnerFrame_Vote struct {
	Vote *Vote `protobuf:"bytes,4,opt,name=vote,proto3,oneof"`
}

type RunnerFrame_Proposal struct {
	Proposal *Proposal `protobuf:"bytes,5,opt,name=proposal,proto3,oneof"`
}

type RunnerFrame_Question struct {
	Question *Question `protobuf:"bytes,6,opt,name=question,proto3,oneof"`
}

type RunnerFrame_Progress struct {
	Progress *Progress `protobuf:"bytes,7,opt,name=progress,proto3,oneof"`
}

type RunnerFrame_Result struct {
	Result *Result `protobuf:"bytes,8,opt,name=result,proto3,oneof"`
}

func (*RunnerFrame_Resume) isRunnerFrame_Body() {}

func (*RunnerFrame_Ack) isRunnerFrame_Body() {}

func (*RunnerFrame_Vote) isRunnerFrame_Body() {}

func (*RunnerFrame_Proposal) isRunnerFrame_Body() {}

func (*RunnerFrame_Question) isRunnerFrame_Body() {}

func (*RunnerFrame_Progress) isRunnerFrame_Body() {}

func (*RunnerFrame_Result) isRunnerFrame_Body() {}

type Assignment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId   string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	AttemptEpoch   uint64                 `protobuf:"varint,2,opt,name=attempt_epoch,json=attemptEpoch,proto3" json:"attempt_epoch,omitempty"`
	ContractHash   string                 `protobuf:"bytes,3,opt,name=contract_hash,json=contractHash,proto3" json:"contract_hash,omitempty"`
	Repository     string                 `protobuf:"bytes,4,opt,name=repository,proto3" json:"repository,omitempty"`
	Branch         string                 `protobuf:"bytes,5,opt,name=branch,proto3" json:"branch,omitempty"`
	BaseCommit     string                 `protobuf:"bytes,6,opt,name=base_commit,json=baseCommit,proto3" json:"base_commit,omitempty"`
	OpenspecChange string                 `protobuf:"bytes,7,opt,name=openspec_change,json=openspecChange,proto3" json:"openspec_change,omitempty"`
	Instruction    string                 `protobuf:"bytes,8,opt,name=instruction,proto3" json:"instruction,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_api_control_v1_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{13}
}

func (x *Assignment) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *Assignment) GetAttemptEpoch() uint64 {
	if x != nil {
		return x.AttemptEpoch
	}
	return 0
}

func (x *Assignment) GetContractHash() string {
	if x != nil {
		return x.ContractHash
	}
	return ""
}

func (x *Assignment) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *Assignment) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *Assignment) GetBaseCommit() string {
	if x != nil {
		return x.BaseCommit
	}
	return ""
}

func (x *Assignment) GetOpenspecChange() string {
	if x != nil {
		return x.OpenspecChange
	}
	return ""
}

func (x *Assignment) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

type CouncilEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DecisionId        string                 `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Round             uint32                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	ProposalHash      string                 `protobuf:"bytes,3,opt,name=proposal_hash,json=proposalHash,proto3" json:"proposal_hash,omitempty"`
	Proposal          []byte                 `protobuf:"bytes,4,opt,name=proposal,proto3" json:"proposal,omitempty"`
	Members           []string               `protobuf:"bytes,5,rep,name=members,proto3" json:"members,omitempty"`
	RequiredApprovals uint32                 `protobuf:"varint,6,opt,name=required_approvals,json=requiredApprovals,proto3" json:"required_approvals,omitempty"`
	State             string                 `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CouncilEvent) Reset() {
	*x = CouncilEvent{}
	mi := &file_api_control_v1_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouncilEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouncilEvent) ProtoMessage() {}

func (x *CouncilEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouncilEvent.ProtoReflect.Descriptor instead.
func (*CouncilEvent) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{14}
}

func (x *CouncilEvent) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *CouncilEvent) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *CouncilEvent) GetProposalHash() string {
	if x != nil {
		return x.ProposalHash
	}
	return ""
}

func (x *CouncilEvent) GetProposal() []byte {
	if x != nil {
		return x.Proposal
	}
	return nil
}

func (x *CouncilEvent) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *CouncilEvent) GetRequiredApprovals() uint32 {
	if x != nil {
		return x.RequiredApprovals
	}
	return 0
}

func (x *CouncilEvent) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type Answer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	AssignmentId  string                 `protobuf:"bytes,2,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	AttemptEpoch  uint64                 `protobuf:"varint,3,opt,name=attempt_epoch,json=attemptEpoch,proto3" json:"attempt_epoch,omitempty"`
	ContractHash  string                 `protobuf:"bytes,4,opt,name=contract_hash,json=contractHash,proto3" json:"contract_hash,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Answer        string                 `protobuf:"bytes,6,opt,name=answer,proto3" json:"answer,omitempty"`
	DecisionId    string                 `protobuf:"bytes,7,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_api_control_v1_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{15}
}

func (x *Answer) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *Answer) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *Answer) GetAttemptEpoch() uint64 {
	if x != nil {
		return x.AttemptEpoch
	}
	return 0
}

func (x *Answer) GetContractHash() string {
	if x != nil {
		return x.ContractHash
	}
	return ""
}

func (x *Answer) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Answer) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *Answer) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

type Receipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_api_control_v1_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{16}
}

func (x *Receipt) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ServerFrame struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	EventId string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Cursor  uint64                 `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*ServerFrame_Assignment
	//	*ServerFrame_Council
	//	*ServerFrame_Answer
	//	*ServerFrame_Receipt
	Body          isServerFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_api_control_v1_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{17}
}

func (x *ServerFrame) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ServerFrame) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ServerFrame) GetBody() isServerFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerFrame) GetAssignment() *Assignment {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Assignment); ok {
			return x.Assignment
		}
	}
	return nil
}

func (x *ServerFrame) GetCouncil() *CouncilEvent {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Council); ok {
			return x.Council
		}
	}
	return nil
}

func (x *ServerFrame) GetAnswer() *Answer {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Answer); ok {
			return x.Answer
		}
	}
	return nil
}

func (x *ServerFrame) GetReceipt() *Receipt {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Receipt); ok {
			return x.Receipt
		}
	}
	return nil
}

type isServerFrame_Body interface {
	isServerFrame_Body()
}

type ServerFrame_Assignment struct {
	Assignment *Assignment `protobuf:"bytes,3,opt,name=assignment,proto3,oneof"`
}

type ServerFrame_Council struct {
	Council *CouncilEvent `protobuf:"bytes,4,opt,name=council,proto3,oneof"`
}

type ServerFrame_Answer struct {
	Answer *Answer `protobuf:"bytes,5,opt,name=answer,proto3,oneof"`
}

type ServerFrame_Receipt struct {
	Receipt *Receipt `protobuf:"bytes,6,opt,name=receipt,proto3,oneof"`
}

func (*ServerFrame_Assignment) isServerFrame_Body() {}

func (*ServerFrame_Council) isServerFrame_Body() {}

func (*ServerFrame_Answer) isServerFrame_Body() {}

func (*ServerFrame_Receipt) isServerFrame_Body() {}

var File_api_control_v1_control_proto protoreflect.FileDescriptor

const file_api_control_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x1capi/control/v1/control.proto\x12\x13botspace.control.v1\"r\n" +
	"\x10ProviderSettings\x12\x16\n" +
	"\x06client\x18\x01 \x01(\tR\x06client\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x16\n" +
	"\x06effort\x18\x04 \x01(\tR\x06effort\"\x87\x02\n" +
	"\x0fPresenceRequest\x12A\n" +
	"\bprovider\x18\x01 \x01(\v2%.botspace.control.v1.ProviderSettingsR\bprovider\x12E\n" +
	"\favailability\x18\x02 \x01(\x0e2!.botspace.control.v1.AvailabilityR\favailability\x12)\n" +
	"\x10project_mappings\x18\x03 \x03(\tR\x0fprojectMappings\x12\x14\n" +
	"\x05tools\x18\x04 \x03(\tR\x05tools\x12)\n" +
	"\x10execution_policy\x18\x05 \x01(\tR\x0fexecutionPolicy\"\xa8\x01\n" +
	"\x10PresenceResponse\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12-\n" +
	"\x04role\x18\x03 \x01(\x0e2\x19.botspace.control.v1.RoleR\x04role\x12)\n" +
	"\x10credential_epoch\x18\x04 \x01(\x04R\x0fcredentialEpoch\"1\n" +
	"\x0eInspectRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\"d\n" +
	"\x0fInspectResponse\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\tR\brevision\"3\n" +
	"\x06Resume\x12)\n" +
	"\x10committed_cursor\x18\x01 \x01(\x04R\x0fcommittedCursor\"8\n" +
	"\x03Ack\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\x04R\x06cursor\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\"z\n" +
	"\x04Vote\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\x12\x14\n" +
	"\x05round\x18\x02 \x01(\rR\x05round\x12#\n" +
	"\rproposal_hash\x18\x03 \x01(\tR\fproposalHash\x12\x16\n" +
	"\x06choice\x18\x04 \x01(\tR\x06choice\"\x9b\x01\n" +
	"\bProposal\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\x12\x14\n" +
	"\x05round\x18\x02 \x01(\rR\x05round\x12+\n" +
	"\x11material_revision\x18\x03 \x01(\tR\x10materialRevision\x12+\n" +
	"\x11canonical_content\x18\x04 \x01(\fR\x10canonicalContent\"\xb4\x01\n" +
	"\bQuestion\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12#\n" +
	"\rattempt_epoch\x18\x02 \x01(\x04R\fattemptEpoch\x12#\n" +
	"\rcontract_hash\x18\x03 \x01(\tR\fcontractHash\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bquestion\x18\x05 \x01(\tR\bquestion\"\x95\x01\n" +
	"\bProgress\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12#\n" +
	"\rattempt_epoch\x18\x02 \x01(\x04R\fattemptEpoch\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\xc9\x01\n" +
	"\x06Result\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12#\n" +
	"\rattempt_epoch\x18\x02 \x01(\x04R\fattemptEpoch\x12#\n" +
	"\rcontract_hash\x18\x03 \x01(\tR\fcontractHash\x12\x16\n" +
	"\x06commit\x18\x04 \x01(\tR\x06commit\x12\x1c\n" +
	"\tartifacts\x18\x05 \x03(\tR\tartifacts\x12\x1a\n" +
	"\bevidence\x18\x06 \x01(\fR\bevidence\"\xb8\x03\n" +
	"\vRunnerFrame\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x125\n" +
	"\x06resume\x18\x02 \x01(\v2\x1b.botspace.control.v1.ResumeH\x00R\x06resume\x12,\n" +
	"\x03ack\x18\x03 \x01(\v2\x18.botspace.control.v1.AckH\x00R\x03ack\x12/\n" +
	"\x04vote\x18\x04 \x01(\v2\x19.botspace.control.v1.VoteH\x00R\x04vote\x12;\n" +
	"\bproposal\x18\x05 \x01(\v2\x1d.botspace.control.v1.ProposalH\x00R\bproposal\x12;\n" +
	"\bquestion\x18\x06 \x01(\v2\x1d.botspace.control.v1.QuestionH\x00R\bquestion\x12;\n" +
	"\bprogress\x18\a \x01(\v2\x1d.botspace.control.v1.ProgressH\x00R\bprogress\x125\n" +
	"\x06result\x18\b \x01(\v2\x1b.botspace.control.v1.ResultH\x00R\x06resultB\x06\n" +
	"\x04body\"\x9f\x02\n" +
	"\n" +
	"Assignment\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12#\n" +
	"\rattempt_epoch\x18\x02 \x01(\x04R\fattemptEpoch\x12#\n" +
	"\rcontract_hash\x18\x03 \x01(\tR\fcontractHash\x12\x1e\n" +
	"\n" +
	"repository\x18\x04 \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06branch\x18\x05 \x01(\tR\x06branch\x12\x1f\n" +
	"\vbase_commit\x18\x06 \x01(\tR\n" +
	"baseCommit\x12'\n" +
	"\x0fopenspec_change\x18\a \x01(\tR\x0eopenspecChange\x12 \n" +
	"\vinstruction\x18\b \x01(\tR\vinstruction\"\xe5\x01\n" +
	"\fCouncilEvent\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\x12\x14\n" +
	"\x05round\x18\x02 \x01(\rR\x05round\x12#\n" +
	"\rproposal_hash\x18\x03 \x01(\tR\fproposalHash\x12\x1a\n" +
	"\bproposal\x18\x04 \x01(\fR\bproposal\x12\x18\n" +
	"\amembers\x18\x05 \x03(\tR\amembers\x12-\n" +
	"\x12required_approvals\x18\x06 \x01(\rR\x11requiredApprovals\x12\x14\n" +
	"\x05state\x18\a \x01(\tR\x05state\"\xf0\x01\n" +
	"\x06Answer\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12#\n" +
	"\rassignment_id\x18\x02 \x01(\tR\fassignmentId\x12#\n" +
	"\rattempt_epoch\x18\x03 \x01(\x04R\fattemptEpoch\x12#\n" +
	"\rcontract_hash\x18\x04 \x01(\tR\fcontractHash\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06answer\x18\x06 \x01(\tR\x06answer\x12\x1f\n" +
	"\vdecision_id\x18\a \x01(\tR\n" +
	"decisionId\"(\n" +
	"\aReceipt\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\xbb\x02\n" +
	"\vServerFrame\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x04R\x06cursor\x12A\n" +
	"\n" +
	"assignment\x18\x03 \x01(\v2\x1f.botspace.control.v1.AssignmentH\x00R\n" +
	"assignment\x12=\n" +
	"\acouncil\x18\x04 \x01(\v2!.botspace.control.v1.CouncilEventH\x00R\acouncil\x125\n" +
	"\x06answer\x18\x05 \x01(\v2\x1b.botspace.control.v1.AnswerH\x00R\x06answer\x128\n" +
	"\areceipt\x18\x06 \x01(\v2\x1c.botspace.control.v1.ReceiptH\x00R\areceiptB\x06\n" +
	"\x04body*C\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eROLE_ARCHITECT\x10\x01\x12\x11\n" +
	"\rROLE_EXECUTOR\x10\x02*u\n" +
	"\fAvailability\x12\x1c\n" +
	"\x18AVAILABILITY_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11AVAILABILITY_FREE\x10\x01\x12\x15\n" +
	"\x11AVAILABILITY_BUSY\x10\x02\x12\x19\n" +
	"\x15AVAILABILITY_DRAINING\x10\x032\x8b\x02\n" +
	"\aControl\x12W\n" +
	"\bPresence\x12$.botspace.control.v1.PresenceRequest\x1a%.botspace.control.v1.PresenceResponse\x12T\n" +
	"\aInspect\x12#.botspace.control.v1.InspectRequest\x1a$.botspace.control.v1.InspectResponse\x12Q\n" +
	"\aConnect\x12 .botspace.control.v1.RunnerFrame\x1a .botspace.control.v1.ServerFrame(\x010\x01B:Z8github.com/petarnenov/bot-space/api/control/v1;controlv1b\x06proto3"

var (
	file_api_control_v1_control_proto_rawDescOnce sync.Once
	file_api_control_v1_control_proto_rawDescData []byte
)

func file_api_control_v1_control_proto_rawDescGZIP() []byte {
	file_api_control_v1_control_proto_rawDescOnce.Do(func() {
		file_api_control_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_control_v1_control_proto_rawDesc), len(file_api_control_v1_control_proto_rawDesc)))
	})
	return file_api_control_v1_control_proto_rawDescData
}

var file_api_control_v1_control_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_control_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_control_v1_control_proto_goTypes = []any{
	(Role)(0),                // 0: botspace.control.v1.Role
	(Availability)(0),        // 1: botspace.control.v1.Availability
	(*ProviderSettings)(nil), // 2: botspace.control.v1.ProviderSettings
	(*PresenceRequest)(nil),  // 3: botspace.control.v1.PresenceRequest
	(*PresenceResponse)(nil), // 4: botspace.control.v1.PresenceResponse
	(*InspectRequest)(nil),   // 5: botspace.control.v1.InspectRequest
	(*InspectResponse)(nil),  // 6: botspace.control.v1.InspectResponse
	(*Resume)(nil),           // 7: botspace.control.v1.Resume
	(*Ack)(nil),              // 8: botspace.control.v1.Ack
	(*Vote)(nil),             // 9: botspace.control.v1.Vote
	(*Proposal)(nil),         // 10: botspace.control.v1.Proposal
	(*Question)(nil),         // 11: botspace.control.v1.Question
	(*Progress)(nil),         // 12: botspace.control.v1.Progress
	(*Result)(nil),           // 13: botspace.control.v1.Result
	(*RunnerFrame)(nil),      // 14: botspace.control.v1.RunnerFrame
	(*Assignment)(nil),       // 15: botspace.control.v1.Assignment
	(*CouncilEvent)(nil),     // 16: botspace.control.v1.CouncilEvent
	(*Answer)(nil),           // 17: botspace.control.v1.Answer
	(*Receipt)(nil),          // 18: botspace.control.v1.Receipt
	(*ServerFrame)(nil),      // 19: botspace.control.v1.ServerFrame
}
var file_api_control_v1_control_proto_depIdxs = []int32{
	2,  // 0: botspace.control.v1.PresenceRequest.provider:type_name -> botspace.control.v1.ProviderSettings
	1,  // 1: botspace.control.v1.PresenceRequest.availability:type_name -> botspace.control.v1.Availability
	0,  // 2: botspace.control.v1.PresenceResponse.role:type_name -> botspace.control.v1.Role
	7,  // 3: botspace.control.v1.RunnerFrame.resume:type_name -> botspace.control.v1.Resume
	8,  // 4: botspace.control.v1.RunnerFrame.ack:type_name -> botspace.control.v1.Ack
	9,  // 5: botspace.control.v1.RunnerFrame.vote:type_name -> botspace.control.v1.Vote
	10, // 6: botspace.control.v1.RunnerFrame.proposal:type_name -> botspace.control.v1.Proposal
	11, // 7: botspace.control.v1.RunnerFrame.question:type_name -> botspace.control.v1.Question
	12, // 8: botspace.control.v1.RunnerFrame.progress:type_name -> botspace.control.v1.Progress
	13, // 9: botspace.control.v1.RunnerFrame.result:type_name -> botspace.control.v1.Result
	15, // 10: botspace.control.v1.ServerFrame.assignment:type_name -> botspace.control.v1.Assignment
	16, // 11: botspace.control.v1.ServerFrame.council:type_name -> botspace.control.v1.CouncilEvent
	17, // 12: botspace.control.v1.ServerFrame.answer:type_name -> botspace.control.v1.Answer
	18, // 13: botspace.control.v1.ServerFrame.receipt:type_name -> botspace.control.v1.Receipt
	3,  // 14: botspace.control.v1.Control.Presence:input_type -> botspace.control.v1.PresenceRequest
	5,  // 15: botspace.control.v1.Control.Inspect:input_type -> botspace.control.v1.InspectRequest
	14, // 16: botspace.control.v1.Control.Connect:input_type -> botspace.control.v1.RunnerFrame
	4,  // 17: botspace.control.v1.Control.Presence:output_type -> botspace.control.v1.PresenceResponse
	6,  // 18: botspace.control.v1.Control.Inspect:output_type -> botspace.control.v1.InspectResponse
	19, // 19: botspace.control.v1.Control.Connect:output_type -> botspace.control.v1.ServerFrame
	17, // [17:20] is the sub-list for method output_type
	14, // [14:17] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_control_v1_control_proto_init() }
func file_api_control_v1_control_proto_init() {
	if File_api_control_v1_control_proto != nil {
		return
	}
	file_api_control_v1_control_proto_msgTypes[12].OneofWrappers = []any{
		(*RunnerFrame_Resume)(nil),
		(*RunnerFrame_Ack)(nil),
		(*RunnerFrame_Vote)(nil),
		(*RunnerFrame_Proposal)(nil),
		(*RunnerFrame_Question)(nil),
		(*RunnerFrame_Progress)(nil),
		(*RunnerFrame_Result)(nil),
	}
	file_api_control_v1_control_proto_msgTypes[17].OneofWrappers = []any{
		(*ServerFrame_Assignment)(nil),
		(*ServerFrame_Council)(nil),
		(*ServerFrame_Answer)(nil),
		(*ServerFrame_Receipt)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_control_v1_control_proto_rawDesc), len(file_api_control_v1_control_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_control_v1_control_proto_goTypes,
		DependencyIndexes: file_api_control_v1_control_proto_depIdxs,
		EnumInfos:         file_api_control_v1_control_proto_enumTypes,
		MessageInfos:      file_api_control_v1_control_proto_msgTypes,
	}.Build()
	File_api_control_v1_control_proto = out.File
	file_api_control_v1_control_proto_goTypes = nil
	file_api_control_v1_control_proto_depIdxs = nil
}
